version: '3.8'
services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
  client:
    build: ./client
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - server
